### ISSUE TITLE
Animations and Weights are bugged

### ISSUE THREAD

**Issue by TheKillerey** [code4game/glTFForUE4#19]
![image](https://user-images.githubusercontent.com/18242778/92624448-cf62e500-f2c7-11ea-9218-2214262c7ad8.png)
This gltf file includes lots of animations and it seems that all animations are loaded together or something. Converting the animations seperatly into Animation Assets would be much better to handle. Weights are also not correct
https://cdn.discordapp.com/attachments/344863946844405760/753288241347821778/2020-09-09_18-16-29.mp4

**Comment by alexchicn** [comment]
Which version do you use? And I tested the animation by the official sample - [BrainStem](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BrainStem).
Or can you send me the gltf file?

**Comment by alexchicn** [comment]
I have known the glTF for UE4 version 1.3 has animation bugs. And I think it was fixed in the latest version 2.0.

Thanks for your comment.

**Comment by alexchicn** [comment]
![UE4Editor_UHHi4qgw5I](https://user-images.githubusercontent.com/2211006/93547739-5125d300-f998-11ea-949f-1aef263738b3.jpg)
![UE4Editor_HkdfobAP9c](https://user-images.githubusercontent.com/2211006/93547755-5aaf3b00-f998-11ea-889c-4b9be3fe5457.jpg)
![UE4Editor_Q7wlMhTZdo](https://user-images.githubusercontent.com/2211006/93547781-6995ed80-f998-11ea-8148-d70d6055827a.jpg)

Under the latest version 2.0 and UE4.25.

**Comment by alexchicn** [comment]
Sorry, the version name is incorrect in the project. I forgot to update it in the `.uplugin`. #20

**Comment by alexchicn** [comment]
![bCbFawADKZ](https://user-images.githubusercontent.com/2211006/93550344-c647d700-f99d-11ea-98d6-d0904f35acd9.gif)

**Comment by TheKillerey** [comment]
All right I will check it out again ^^
