### ISSUE TITLE
Importing sceleton from blender

### ISSUE THREAD

**Issue by pinq-** [code4game/glTFForUE4#22]
Hi,

Can you give my a hind, how to get skeleton/armature from blender to UN4? I can't figure out, why can't I export and then import armature. Meshes and materials are good, but I can't play my animation.

**Comment by jixingcn** [comment]
UN4? Do you mean UE4?
You can export the blender scene to glTF binary, then check it by the 3D viewer in windows 10 or [glTF viewer](https://gltf-viewer.donmccurdy.com/).
Does your glTF is available?

**Comment by pinq-** [comment]
Sorry, yes UE4. 
I did try to export again and then import to blender, but it makes all the bones to empties and there is no skeleton at all.

**Comment by jixingcn** [comment]
So I think it has problems when you export the glTF from the blender.

**Comment by jixingcn** [comment]
Thanks for your comment.

**Comment by pinq-** [comment]
Yes, the problem is when I export it? Is there something that I should know about this?

**Comment by jixingcn** [comment]
> Yes, the problem is when I export it? Is there something that I should know about this?

Yes, I think. Any other glb viewers are available?
