### ISSUE TITLE
Right-click reload mesh in the Editor ?

### ISSUE THREAD

**Issue by motorsep** [code4game/glTFForUE4#32]
Would it be possible to have a menu option to reload mesh in the scene via right click menu ?
Imagine working on a level in Blender and continuously iterating. Having Mesh Editor (static or skeletal) open is fine, but it would be a lot quicker and less effort on the level designer's part to simply right click on the geometry in the Editor's viewport, select Reload Geometry menu item and have mesh instantly updated in the scene.

**Comment by jixingcn** [comment]
You want to reimport the mesh that is created from the glTF file in the level editor. Am I right?

**Comment by motorsep** [comment]
> You want to reimport the mesh that is created from the glTF file in the level editor. Am I right?

Yep.

**Comment by jixingcn** [comment]
Yes, your idea is reasonable in some cases, and I know how to add it into the right menu to reimport the mesh by this plugin. But I don't think it should be implemented in this plugin, and it should allow reimporting other assets like jpeg, png, fbx, etc. This plugin focus on the integration of glTF and UE4.
My suggestion is to submit or share your idea in the unreal engine forum.
