### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by Fr0zka** [code4game/glTFForUE4#36]
Hey i've tried to load a glTF file with your plugin, everything seemed to work properly, but now its been ~ 10 minute and its still stuck on 
![Sans titre](https://user-images.githubusercontent.com/37193623/107243820-b18fdc80-6a2d-11eb-8102-fe23fa0f1047.png)

is it normal ? :c (my glTF is about ~600mb)

(ue4 4.26.1 and your latest plugin version)

(after 20~ minute i've tried with a .gltf instead of .glb, this time, unreal crashed after few seconds)

**Comment by jixingcn** [comment]
@Fr0zka  Yes, it's not reasonable.
Can you send the log to me or describe the content of your glTF file? You can find log files in `[YourProject]\Saved\Log` folder.

**Comment by Fr0zka** [comment]
I'm uploading the .gltf file right now, but there is the log for now ^^'

[Hide.log](https://github.com/code4game/glTFForUE4/files/5949993/Hide.log)

**Comment by jixingcn** [comment]
@Fr0zka Ok, I got. Give me time to check.

**Comment by jixingcn** [comment]
Ok, I know the reason. The glTF file contains about 1600+ objects. For each asset, it will recalculate the md5 value that is generated by the glTF file. The glTF is too big to spend about 1 second to calculate the MD5 value. So it does that about 1600+ times 😵 , it will cost about 20 mins 😢  (also depend on your machine).

And I import it after I fix it and cost about 6 mins 😃  on my laptop.

![image](https://user-images.githubusercontent.com/33065325/107352770-37cc2180-6b07-11eb-946c-5ee11b4e8094.png)

I will fix it in the next version 2.0.6.

**Comment by jixingcn** [comment]
@Fr0zka Does Does the unreal crash when importing the glb file? Can you share the glb file?

**Comment by Fr0zka** [comment]
Ooohh nice ^^ can't wait for this next update, and i think unreal crashed because i had not enought free ram when i tried. 
It never crashed again when trying to load glb/glbf o:

(+ i see that every object have the right position on map o: i'm pretty hyped)

**Comment by jixingcn** [comment]
@Fr0zka Ok, now you can download the new version. It was deployed to [itch.io](https://c4gio.itch.io/gltf-for-ue4).
