### ISSUE TITLE
Unreal Crash when i try to import gltf with animation / skeletal mesh

### ISSUE THREAD

**Issue by Fr0zka** [code4game/glTFForUE4#37]
So....... this time i've tried to import this -> 
https://wow.tools/mv/?buildconfig=081460ab8f317f8273068b29288f2af7&cdnconfig=a00c4591f68ddf55d8baa84db360a8d0&filedataid=189282&type=m2

[smelter.zip](https://github.com/code4game/glTFForUE4/files/5961515/smelter.zip)

but i really can't import it, unreal crash everytime i have the skeletal mesh option on x: 

(i'm maybe the one who don't know how to use this but mhhh...)

log : 
[Hide_2.log](https://github.com/code4game/glTFForUE4/files/5961586/Hide_2.log)

(edit: ok so it was an unreal issue when you have multiple bone with no root.... my bad, but still my animation not working, but ... thats maybe my bad so i close this issue xD)

**Comment by jixingcn** [comment]
And I found that the byte offset of the accessor is incorrect in the glTF file 😞.

**Comment by Fr0zka** [comment]
I don't even know what it is... x')

**Comment by jixingcn** [comment]
Thanks a lot. I found another fatal bug #38.

**Comment by jixingcn** [comment]
Import as a static mesh:

![image](https://user-images.githubusercontent.com/33065325/107883277-fd102200-6f28-11eb-9846-a45fb48bbcde.png)

**Comment by jixingcn** [comment]
By the way, I will fix this in next version 2.0.8. #40

**Comment by Fr0zka** [comment]
Congrats ^^
