### ISSUE TITLE
Any plans to support runtime import

### ISSUE THREAD

**Issue by tonetechnician** [code4game/glTFForUE4#46]
Hi there! 

Thanks for making this plugin available! I was just wondering if there are any thoughts to make this plugin support runtime import?

**Comment by jixingcn** [comment]
Yes, I have plans to support import in runtime.

If you want to import the glTF in runtime, you can try this plugin - [glTFRuntime](https://github.com/rdeioris/glTFRuntime).

**Comment by tonetechnician** [comment]
Amazing! Thanks for the fast response. That's really good to know! Is there a timeline on when it might be ready? Anything I could do to help speed it alog?

I've been using glTFRuntime, but it doesn't have great performance (i.e assets take long to load) and no support for draco compressed meshes.

**Comment by jixingcn** [comment]
In my plan, it will be supported in v4.0. Now I don't have time to do the "load-in-runtime", so the task isn't created in the milestone list and I can't make any promise.

You can submit issues about performance and draco in [glTFRuntime](https://github.com/rdeioris/glTFRuntime).

* **About the performance of [glTFRuntime](https://github.com/rdeioris/glTFRuntime)**, you can see [https://github.com/rdeioris/glTFRuntime/issues/3](https://github.com/rdeioris/glTFRuntime/issues/3), [rdeioris](https://github.com/rdeioris) said `Finally, regarding performance, there are still optimization areas, but yes, the main time is spent in the various optimizations/checks made by unreal. For staticmeshes we can cut down time a bit with the ProceduralMeshComponent at the cost of higher rendering time. maybe this could be another option to add`. So I don't think my plugin's performance will be better than the [glTFRuntime](https://github.com/rdeioris/glTFRuntime) if I support the "load-in-runtime".
