### ISSUE TITLE
4.22 support?

### ISSUE THREAD

**Issue by NazzarenoGiannelli** [code4game/glTFForUE4#6]
I wanted to install your plugin as a submodule for one of my repositories so I cloned it directly from GitHub, but when I launch the uproject I get a warning telling me that the modules glTFForUE4 and glTFForUE4Ed are missing or built with a different engine version.
Did you update the version here on GitHub with the latest one compatible with 4.22?

**Comment by koloved** [comment]
i got same issue with 4.22.1 :'(

**Comment by shogundr4g0n** [comment]
Issue persists on 4.22.2

**Comment by alexchicn** [comment]
Can you tell me the warning message?
I think you need to run this command to replace the `.cs` file.
```batch
python "%PROJECT_DIR%/Plugins/glTFForUE4/Extras/Batch/SetupForUE4Project.py" "%PROJECT_DIR%/Plugins/glTFForUE4/Extras/Batch/SetupForUE4Project.ini" 4.22
```

**Comment by alexchicn** [comment]
I already release the binary package for UE4.22 in [itchio](https://c4gio.itch.io/gltf-for-ue4), and you can download directly it.

**Comment by Novezeil** [comment]
Issue persists in 4.22.2, binary package supplied cannot be used in conjunction with stock UE.

**Comment by alexchicn** [comment]
I think I know the problem. I packaged the binary package when the UE4.22 is a preview version, but it is different between the released and preview version.
I am as soon as possible to repackage it again.

**Comment by alexchicn** [comment]
Just repackage/rebuild it. Download it from [https://c4gio.itch.io/gltf-for-ue4](https://c4gio.itch.io/gltf-for-ue4).
