### ISSUE TITLE
Vertecies messed up, Skeletal mesh UE5

### ISSUE THREAD

**Issue by D3fa1t1** [code4game/glTFForUE4#60]
![image](https://user-images.githubusercontent.com/77608590/189189241-56d6670e-ef99-41be-8442-19af8128a57a.png)
This is Unreal Engine Version 5.0.3, i am using the UE5 Build from Itch.io.
the file is supposed to look like this instead 
![image](https://user-images.githubusercontent.com/77608590/189190686-2f1dcd27-5004-4f51-858b-85e78136f428.png)

Here is the mesh its a gltf and binary file: https://drive.google.com/drive/folders/1rubDRYYEroYu2nvIMbhP0m9i6BSAgOgL?usp=sharing
if you put this into the GLTF viewer found online, the vertecies display fine [which is [here](https://gltf-viewer.donmccurdy.com/)]

**Comment by Sunz-CNKK** [comment]
Similar behavior here tooSimilar behavior here too

**Comment by liuhuagang** [comment]
Hava Some Behavior in4.27,4.26,How should I do?

**Comment by D3fa1t1** [comment]
oh god this is a big problem

**Comment by liuhuagang** [comment]
I hava tried 5.0.3,and 4.27.2,4.26,4.24. If I tend to import glb to ue ,hoping to generate SkeletalMesh,It will be a big problem. these points are not all in right place.However ,5.1 can import glb directly.we can only use other ways.

**Comment by jixingcn** [comment]
> I hava tried 5.0.3,and 4.27.2,4.26,4.24. If I tend to import glb to ue ,hoping to generate SkeletalMesh,It will be a big problem. these points are not all in right place.However ,5.1 can import glb directly.we can only use other ways.

Sorry for being late. I will check it recently.
I would be glad if 5.1 supports it and can solve your problem.

**Comment by jixingcn** [comment]
I solve that.

![issue60-skeleton](https://user-images.githubusercontent.com/33065325/217192244-1444c220-e4ec-4c11-bcad-56fbae28d412.JPG)

I commit the fix to the build machine and am ready to publish v2.0.12.

**Comment by jixingcn** [comment]
The big problem is solved. Glad to try the new version 2.0.12. @D3fa1t1 @liuhuagang @Sunz-CNKK
