### ISSUE TITLE
Does this coexist with built-in gltf plugin?

### ISSUE THREAD

**Issue by OptimisticMonkey** [code4game/glTFForUE4#66]
Do you have to disable the builtin gltf plugin from epic?  It has a bunch of dependent plugins like interchange.  Or can it coexist at same time?

**Comment by jixingcn** [comment]
I remember that the official gltf importer is disabled as the default. In my project, I don't change that and my plugin is effective.
**The effective importer depends on the order of the plugin registration when they coexist and enable.**
Do you have any problems when you enable both?
I never enable both of them.
