### ISSUE TITLE
Mac build ?

### ISSUE THREAD

**Issue by gedw99** [code4game/glTFForUE4#68]
I noticed that the last few releases did not have a Mac version. Only windows.

**Comment by jixingcn** [comment]
Yes, sorry about that. My mac-mini is too old and slow for building, so I have to pay a lot of time waiting. 😞
And I don't know how many people work in mac. I think that it can be compiled on a mac without any errors now.

I will build the mac version again if someone still needs a mac version.

**Comment by jixingcn** [comment]
I think it is not necessary to build the Mac version.
